version: '3'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Haeg1iez
  web:
    build: .
    command: ['./wait-for-postgres.sh', "db", "bin/server-start"]
    volumes:
      - .:/teamvite
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
       DATABASE_URL: postgres://postgres:Haeg1iez@db:5432/teamvite
    restart: always
volumes:
  db-data:
