version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bin/server-start
    volumes:
      - .:/teamvite
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
       DATABASE_URL: postgres://postgres@db:5432/teamvite?encoding=unicode
