version: '3'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Haeg1iez
    ports:
      - "127.0.0.1:5432:5432"
  web:
    build: .
    command: ['bin/wait-for-postgres.sh', "db", "bin/server-start"]
    domainname: teamvite.home.arpa
    volumes:
      - .:/teamvite
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
    environment:
       DATABASE_URL: postgres://postgres:Haeg1iez@db:5432/teamvite
       RACK_ENV: development
    restart: always
volumes:
  db-data:
