production:
  db:
    adapter: postgres
    password: f0rd.Tough
    username: picklespears
    database: picklespears

development:
  db:
    adapter: postgres
    password: f0rd.Tough
    username: picklespears
    database: picklespears
    logfile: '/tmp/picklespearsdev.log'

test:
  db:
    adapter: postgres
    password: f0rd.Tough
    username: picklespears
    database: picklespearstest
    logfile: '/tmp/picklespearstest.log'
