production:
  adapter: postgres
  database: picklespears
  username: test
  password: test

development:
  adapter: postgres
  database: picklespearsdev

test:
  adapter: sqlite3
  database: picklespearstest
